// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oyheezfoazrhqusyoibw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95aGVlemZvYXpyaHF1c3lvaWJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NDY0NzAsImV4cCI6MjA2MTEyMjQ3MH0.VDzmDN-B21A-pF520UVJeauuhrRDqH_twA8aSnc0LMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);